### ISSUE TITLE
Broker-side error when connecting client to the ActiveMQ

### ISSUE THREAD

**Issue by hekonsek** [vert-x3/vertx-proton#13]
Hi,

I can connect Vert.x Proton client to Vert.x Proton server. However when I try to connect the same client to the ActiveMQ-based AMQP server, I get the server side exception. 

I'm using the latest ActiveMQ and the latest Vert.x Proton client.

Code to reproduce the issue:

```
package test;

import io.vertx.core.Vertx;
import io.vertx.proton.ProtonClient;
import io.vertx.proton.ProtonConnection;
import io.vertx.proton.ProtonSender;
import org.apache.activemq.broker.BrokerService;
import org.apache.qpid.proton.message.Message;

import static io.vertx.proton.ProtonHelper.message;
import static io.vertx.proton.ProtonHelper.tag;

public class BrokerClient {

    public static void main(String[] args) throws Exception {
        BrokerService broker = new BrokerService();
        broker.setPersistent(false);
        broker.addConnector("amqp://0.0.0.0:9999");
        broker.start();

        Vertx vertx = Vertx.vertx();
        ProtonClient client = ProtonClient.create(vertx);
        client.connect("localhost", 9999, res -> {
            if (res.succeeded()) {
                ProtonConnection connection = res.result();
                ProtonSender sender = connection.createSender("foo");
                sender.open();
                Message message = message("Hello World from client");
                sender.send(tag("m1"), message, delivery -> {
                    System.out.println("The message was received by the server");
                });
            } else {
                res.cause().printStackTrace();
            }
        });
    }

}
```

The exception I see on the broker side:

```
The message was received by the server
20:57:30.985 [ActiveMQ Transport: tcp:///127.0.0.1:57214@9999] DEBUG o.a.a.t.amqp.protocol.AmqpSession - Session ID:henryberg-40533-1456171049911-3:1:0 opened
20:57:30.995 [ActiveMQ Transport: tcp:///127.0.0.1:57214@9999] DEBUG o.a.a.t.amqp.protocol.AmqpSession - opening new receiver ID:henryberg-40533-1456171049911-3:1:0:0 on link: auto-0
20:57:31.008 [ActiveMQ Transport: tcp:///127.0.0.1:57214@9999] DEBUG o.a.a.b.TransportConnection.Service - Error occured while processing sync command: ProducerInfo {commandId = 2, responseRequired = true, producerId = ID:henryberg-40533-1456171049911-3:1:0:0, destination = queue://foo, brokerPath = null, dispatchAsync = false, windowSize = 0, sentCount = 0}, exception: java.lang.IllegalStateException: Cannot add a producer to a connection that had not been registered: ID:henryberg-40533-1456171049911-3:1
java.lang.IllegalStateException: Cannot add a producer to a connection that had not been registered: ID:henryberg-40533-1456171049911-3:1
	at org.apache.activemq.broker.TransportConnection.processAddProducer(TransportConnection.java:599) ~[activemq-broker-5.13.1.jar:5.13.1]
	at org.apache.activemq.command.ProducerInfo.visit(ProducerInfo.java:108) ~[activemq-client-5.13.1.jar:5.13.1]
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:338) ~[activemq-broker-5.13.1.jar:5.13.1]
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:188) [activemq-broker-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.TransportFilter.onCommand(TransportFilter.java:69) [activemq-client-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.amqp.AmqpTransportFilter.sendToActiveMQ(AmqpTransportFilter.java:122) [activemq-amqp-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.amqp.protocol.AmqpConnection.sendToActiveMQ(AmqpConnection.java:779) [activemq-amqp-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.amqp.protocol.AmqpSession.createReceiver(AmqpSession.java:199) [activemq-amqp-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.amqp.protocol.AmqpConnection.processLinkOpen(AmqpConnection.java:551) [activemq-amqp-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.amqp.protocol.AmqpConnection.processProtonEvents(AmqpConnection.java:405) [activemq-amqp-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.amqp.protocol.AmqpConnection.onAMQPData(AmqpConnection.java:371) [activemq-amqp-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.amqp.AmqpTransportFilter.onCommand(AmqpTransportFilter.java:106) [activemq-amqp-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83) [activemq-client-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:233) [activemq-client-5.13.1.jar:5.13.1]
	at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215) [activemq-client-5.13.1.jar:5.13.1]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Feb 22, 2016 8:57:31 PM io.vertx.proton.impl.ProtonSessionImpl
WARNING: Sender closed with error
io.vertx.core.impl.NoStackTraceThrowable: Error{condition=amqp:internal-error, description='Cannot add a producer to a connection that had not been registered: ID:henryberg-40533-1456171049911-3:1', info=null}
```

Do I need to add something to the configuration of my client?

Cheers!

**Comment by gemmellr** [comment]
I think you need to open the Connection itself. There was a proton-j defect
around this which I fixed in 0.12.0, in that it shouldn't actually have
asked the server to begin a session (hidden here) or attach the sender link
at that point because the connection wasn't opened.

**Comment by hekonsek** [comment]
Yay! Opening the connection explicitly did the trick. Many thanks, Robbie!

**Comment by gemmellr** [comment]
Added duplicate label to avoid the Issue being in release notes.
